(() => {
  const form=document.getElementById('therapistBuilder'); if(!form) return;
  const steps=[...document.querySelectorAll('.build-step')], dots=[...document.querySelectorAll('.step-track span')];
  const next=document.getElementById('nextStep'), back=document.getElementById('backStep'); let current=0;
  const selected=document.getElementById('selectedTreatments');
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function renderStep(){steps.forEach((x,i)=>x.classList.toggle('active',i===current));dots.forEach((x,i)=>x.classList.toggle('active',i<=current));back.disabled=current===0;next.textContent=current===steps.length-1?'Submit for review':'Continue'; if(current===steps.length-1) preview(); window.scrollTo({top:0,behavior:'smooth'});}
  function addTreatment(name){if(!name||[...selected.querySelectorAll('[data-name]')].some(x=>x.dataset.name===name))return; selected.querySelector('.empty-menu')?.remove(); const row=document.createElement('div');row.className='treatment-row';row.dataset.name=name;row.innerHTML=`<b>${esc(name)}</b><label>Minutes<input type="number" min="10" step="5" value="60" aria-label="${esc(name)} duration"></label><label>Price £<input type="number" min="0" step="1" placeholder="55" aria-label="${esc(name)} price"></label><button type="button" class="remove-treatment">Remove</button>`;selected.appendChild(row); row.querySelector('.remove-treatment').onclick=()=>{row.remove();document.querySelector(`[data-treatment="${CSS.escape(name)}"]`)?.classList.remove('selected');if(!selected.children.length)selected.innerHTML='<div class="empty-menu">No treatments added yet.</div>';};}
  document.querySelectorAll('[data-treatment]').forEach(b=>b.onclick=()=>{b.classList.add('selected');addTreatment(b.dataset.treatment)});
  const add=document.getElementById('addCustomTreatment'); add.onclick=()=>{const i=document.getElementById('customTreatment');addTreatment(i.value.trim());i.value=''};
  const search=document.getElementById('treatmentSearch'); search.addEventListener('input',()=>{const q=search.value.toLowerCase();document.querySelectorAll('.treatment-library section').forEach(sec=>{let visible=0;sec.querySelectorAll('[data-treatment]').forEach(b=>{const show=b.textContent.toLowerCase().includes(q);b.style.display=show?'':'none';visible+=show});sec.style.display=visible?'':'none'})});
  function preview(){const d=new FormData(form);document.getElementById('pvName').textContent=d.get('displayName')||d.get('business')||'Your name';document.getElementById('pvPlace').textContent=[d.get('city'),d.get('postcode')].filter(Boolean).join(' · ')||'Your location';document.getElementById('pvAbout').textContent=d.get('about')||'Your introduction will appear here.';const rows=[...selected.querySelectorAll('[data-name]')];document.getElementById('pvTreatments').innerHTML=rows.map(r=>`<span>${esc(r.dataset.name)}</span>`).join('');const prices=rows.map(r=>+r.querySelectorAll('input')[1].value).filter(x=>x>0);document.getElementById('pvPrice').textContent=prices.length?`Treatments from £${Math.min(...prices)}`:'';}
  next.onclick=()=>{if(current<steps.length-1){current++;renderStep()}else{next.disabled=true;next.textContent='Ready for live system';const msg=document.createElement('div');msg.className='submit-note';msg.textContent='Prototype complete — your profile is ready for the future review system.';next.parentElement.appendChild(msg)}};
  back.onclick=()=>{if(current>0){current--;renderStep()}};
  renderStep();
})();
